import type { GatewayProvider } from "./gateway.js";

export type CommercialUseStatus = "approved" | "review_required" | "blocked";
export type AdapterStatus = "live" | "implemented" | "planned" | "not_applicable";
export type SourceQuality = "official" | "primary" | "aggregator" | "community";

export interface SourceProvider extends GatewayProvider {
  category: string;
  auth: "none" | "optional-contact" | "api-key" | "oauth" | "user-agent";
  baseUrl: string;
  commercialUse: CommercialUseStatus;
  freeTierUse: "production_allowed" | "evaluation_only" | "not_available" | "not_applicable" | "unknown";
  sourceQuality: SourceQuality;
  adapterStatus: AdapterStatus;
  secretEnvName?: string;
  quota?: string;
  freshnessPolicy: string;
  regionCoverage: string[];
  termsUrl: string;
  documentationUrl: string;
  reviewedAt: string;
  reviewNotes?: string;
}

const reviewedAt = "2026-08-15";
const provider = (value: SourceProvider): SourceProvider => value;

export const sourceRegistry: readonly SourceProvider[] = Object.freeze([
  provider({ id:"gdelt-doc",name:"GDELT DOC 2.0",category:"news",capabilities:["news-discovery"],status:"approved",auth:"none",baseUrl:"https://api.gdeltproject.org",commercialUse:"approved",freeTierUse:"production_allowed",sourceQuality:"aggregator",priority:10,adapterStatus:"live",attribution:"GDELT Project",freshnessPolicy:"query-window",regionCoverage:["global"],dataBoundary:"Discovery metadata only. Linked publisher content must be independently verified.",termsUrl:"https://www.gdeltproject.org/about.html#termsofuse",documentationUrl:"https://blog.gdeltproject.org/gdelt-doc-2-0-api-debuts/",reviewedAt }),
  provider({ id:"crossref",name:"Crossref REST API",category:"scholarly",capabilities:["scholarly-discovery"],status:"approved",auth:"optional-contact",baseUrl:"https://api.crossref.org",commercialUse:"approved",freeTierUse:"production_allowed",sourceQuality:"primary",priority:10,adapterStatus:"live",freshnessPolicy:"deposit-metadata",regionCoverage:["global"],dataBoundary:"Bibliographic metadata only; do not assume abstract or full-text rights.",termsUrl:"https://www.crossref.org/documentation/retrieve-metadata/rest-api/rest-api-metadata-license-information/",documentationUrl:"https://www.crossref.org/documentation/retrieve-metadata/rest-api/",reviewedAt }),
  provider({ id:"datacite",name:"DataCite REST API",category:"scholarly",capabilities:["scholarly-discovery"],status:"approved",auth:"none",baseUrl:"https://api.datacite.org",commercialUse:"approved",freeTierUse:"production_allowed",sourceQuality:"primary",priority:20,adapterStatus:"live",attribution:"DataCite",freshnessPolicy:"doi-metadata",regionCoverage:["global"],dataBoundary:"CC0 DOI metadata only; linked resources retain their own rights.",termsUrl:"https://support.datacite.org/docs/datacite-data-file-use-policy",documentationUrl:"https://support.datacite.org/docs/api",reviewedAt }),
  provider({ id:"sec-edgar",name:"SEC EDGAR",category:"company-data",capabilities:["company-filings"],status:"approved",auth:"user-agent",baseUrl:"https://data.sec.gov",commercialUse:"approved",freeTierUse:"production_allowed",sourceQuality:"official",priority:10,adapterStatus:"planned",quota:"Maximum 10 requests/second; declared User-Agent required.",freshnessPolicy:"filings-typically-available-within-minutes",regionCoverage:["US","foreign-issuers-filing-with-SEC"],dataBoundary:"Public filing/submission data only; respect SEC fair-access policy and caching.",termsUrl:"https://www.sec.gov/about/developer-resources",documentationUrl:"https://www.sec.gov/search-filings/edgar-application-programming-interfaces",reviewedAt }),
  provider({ id:"companies-house",name:"UK Companies House API",category:"company-data",capabilities:["company-registry"],status:"approved",auth:"api-key",baseUrl:"https://api.company-information.service.gov.uk",commercialUse:"approved",freeTierUse:"production_allowed",sourceQuality:"official",priority:10,adapterStatus:"planned",secretEnvName:"NEO_COMPANIES_HOUSE_KEY",quota:"600 requests per 5 minutes by default.",freshnessPolicy:"live-real-time-public-register",regionCoverage:["UK"],dataBoundary:"Public Companies House records only; credentials stay server-side.",termsUrl:"https://developer.company-information.service.gov.uk/developer-guidelines/",documentationUrl:"https://developer.company-information.service.gov.uk/",reviewedAt }),
  provider({ id:"ecb-data-portal",name:"ECB Data Portal API",category:"economic-data",capabilities:["economic-data","fx-rates"],status:"approved",auth:"none",baseUrl:"https://data-api.ecb.europa.eu",commercialUse:"approved",freeTierUse:"production_allowed",sourceQuality:"official",priority:10,adapterStatus:"planned",attribution:"Source: ECB statistics.",freshnessPolicy:"series-defined",regionCoverage:["EU","global-fx-reference-rates"],dataBoundary:"Public ESCB statistics only; quote source and exclude uncleared third-party data.",termsUrl:"https://www.ecb.europa.eu/stats/ecb_statistics/governance_and_quality_framework/html/usage_policy.en.html",documentationUrl:"https://data.ecb.europa.eu/help/api/overview",reviewedAt }),
  provider({ id:"world-bank-indicators",name:"World Bank Indicators API",category:"economic-data",capabilities:["economic-data","open-data"],status:"approved",auth:"none",baseUrl:"https://api.worldbank.org",commercialUse:"approved",freeTierUse:"production_allowed",sourceQuality:"official",priority:20,adapterStatus:"planned",attribution:"The World Bank",freshnessPolicy:"dataset-defined",regionCoverage:["global"],dataBoundary:"Use only datasets whose metadata permits reuse; third-party indicators may carry separate restrictions.",termsUrl:"https://www.worldbank.org/ext/en/legal/terms-conditions/datasets",documentationUrl:"https://datahelpdesk.worldbank.org/knowledgebase/articles/889392-about-the-indicators-api-documentation",reviewedAt }),
  provider({ id:"data-gov-catalog",name:"Data.gov Catalog API",category:"government-open-data",capabilities:["government-open-data-discovery"],status:"approved",auth:"api-key",baseUrl:"https://api.gsa.gov",commercialUse:"approved",freeTierUse:"production_allowed",sourceQuality:"official",priority:10,adapterStatus:"planned",secretEnvName:"NEO_DATA_GOV_KEY",freshnessPolicy:"catalog-metadata",regionCoverage:["US"],dataBoundary:"Catalog metadata only; underlying dataset licences remain authoritative.",termsUrl:"https://api.data.gov/terms/",documentationUrl:"https://resources.data.gov/catalog-api/",reviewedAt }),
  provider({ id:"met-norway-weather",name:"MET Norway WeatherAPI",category:"weather",capabilities:["weather-forecast"],status:"approved",auth:"user-agent",baseUrl:"https://api.met.no",commercialUse:"approved",freeTierUse:"production_allowed",sourceQuality:"official",priority:10,adapterStatus:"planned",attribution:"MET Norway / source dataset attribution required",freshnessPolicy:"forecast-product-defined",regionCoverage:["global-location-forecast"],dataBoundary:"Open weather data; identify client, attribute source, cache responsibly and avoid confidential location data.",termsUrl:"https://api.met.no/doc/TermsOfService",documentationUrl:"https://api.met.no/weatherapi/documentation",reviewedAt }),
  provider({ id:"google-public-dns",name:"Google Public DNS JSON API",category:"network",capabilities:["dns-resolution"],status:"approved",auth:"none",baseUrl:"https://dns.google",commercialUse:"approved",freeTierUse:"production_allowed",sourceQuality:"official",priority:10,adapterStatus:"planned",freshnessPolicy:"dns-ttl",regionCoverage:["global"],dataBoundary:"DNS resolution only; do not submit confidential domain names.",termsUrl:"https://developers.google.com/speed/public-dns/terms",documentationUrl:"https://developers.google.com/speed/public-dns/docs/doh/json",reviewedAt }),
  provider({ id:"serpapi",name:"SerpApi Google Search API",category:"seo",capabilities:["seo-serp-discovery"],status:"experimental",auth:"api-key",baseUrl:"https://serpapi.com",commercialUse:"review_required",freeTierUse:"evaluation_only",sourceQuality:"aggregator",priority:10,adapterStatus:"live",secretEnvName:"NEO_SERPAPI_KEY",freshnessPolicy:"live-or-provider-cache",regionCoverage:["global"],dataBoundary:"SERP metadata only; result counts are not search volume or keyword difficulty.",termsUrl:"https://serpapi.com/legal",documentationUrl:"https://serpapi.com/search-api",reviewedAt }),
  provider({ id:"zenserp",name:"Zenserp Google Search API",category:"seo",capabilities:["seo-serp-discovery"],status:"experimental",auth:"api-key",baseUrl:"https://app.zenserp.com",commercialUse:"review_required",freeTierUse:"evaluation_only",sourceQuality:"aggregator",priority:20,adapterStatus:"live",secretEnvName:"NEO_ZENSERP_KEY",freshnessPolicy:"live-serp",regionCoverage:["global"],dataBoundary:"SERP metadata only; snippets/descriptions excluded from Neo payloads.",termsUrl:"https://zenserp.com/terms",documentationUrl:"https://app.zenserp.com/documentation",reviewedAt }),
  provider({ id:"serper",name:"Serper Google Search API",category:"seo",capabilities:["seo-serp-discovery"],status:"experimental",auth:"api-key",baseUrl:"https://google.serper.dev",commercialUse:"review_required",freeTierUse:"evaluation_only",sourceQuality:"aggregator",priority:30,adapterStatus:"planned",secretEnvName:"NEO_SERPER_KEY",freshnessPolicy:"live-serp",regionCoverage:["global"],dataBoundary:"Candidate until commercial-use terms and normalized adapter contract are cleared.",termsUrl:"https://serper.dev/terms",documentationUrl:"https://serper.dev/",reviewedAt }),
  provider({ id:"arbeitnow-jobs",name:"Arbeitnow Job Board API",category:"jobs",capabilities:["jobs-discovery"],status:"experimental",auth:"none",baseUrl:"https://www.arbeitnow.com",commercialUse:"review_required",freeTierUse:"unknown",sourceQuality:"aggregator",priority:10,adapterStatus:"planned",freshnessPolicy:"current-job-board",regionCoverage:["Europe","remote"],dataBoundary:"Job-discovery metadata only; commercial reuse rights require confirmation.",termsUrl:"https://www.arbeitnow.com/terms",documentationUrl:"https://www.arbeitnow.com/blog/job-board-api",reviewedAt }),
  provider({ id:"adzuna-jobs",name:"Adzuna API",category:"jobs",capabilities:["jobs-discovery"],status:"experimental",auth:"api-key",baseUrl:"https://api.adzuna.com",commercialUse:"review_required",freeTierUse:"evaluation_only",sourceQuality:"aggregator",priority:20,adapterStatus:"planned",secretEnvName:"NEO_ADZUNA_KEY",freshnessPolicy:"provider-defined",regionCoverage:["multiple-countries"],dataBoundary:"Ongoing organisational commercial use may require consent/licence.",termsUrl:"https://developer.adzuna.com/docs/terms_of_service",documentationUrl:"https://developer.adzuna.com/",reviewedAt }),
  provider({ id:"alpha-vantage",name:"Alpha Vantage",category:"market-data",capabilities:["market-data","fx-rates","crypto-market-data"],status:"experimental",auth:"api-key",baseUrl:"https://www.alphavantage.co",commercialUse:"review_required",freeTierUse:"evaluation_only",sourceQuality:"aggregator",priority:20,adapterStatus:"planned",secretEnvName:"NEO_ALPHA_VANTAGE_KEY",freshnessPolicy:"endpoint-and-entitlement-defined",regionCoverage:["global-markets"],dataBoundary:"Free/personal entitlements are not approved for Neo commercial production.",termsUrl:"https://www.alphavantage.co/terms_of_service/",documentationUrl:"https://www.alphavantage.co/documentation/",reviewedAt }),
  provider({ id:"twelve-data",name:"Twelve Data",category:"market-data",capabilities:["market-data","fx-rates","crypto-market-data"],status:"experimental",auth:"api-key",baseUrl:"https://api.twelvedata.com",commercialUse:"review_required",freeTierUse:"not_available",sourceQuality:"aggregator",priority:30,adapterStatus:"planned",secretEnvName:"NEO_TWELVE_DATA_KEY",freshnessPolicy:"subscription-defined",regionCoverage:["global-markets"],dataBoundary:"Free-tier data is not for commercial use; external display/redistribution requires rights.",termsUrl:"https://twelvedata.com/terms",documentationUrl:"https://twelvedata.com/docs",reviewedAt }),
  provider({ id:"coingecko",name:"CoinGecko API",category:"crypto",capabilities:["crypto-market-data"],status:"experimental",auth:"api-key",baseUrl:"https://api.coingecko.com",commercialUse:"review_required",freeTierUse:"unknown",sourceQuality:"aggregator",priority:10,adapterStatus:"planned",secretEnvName:"NEO_COINGECKO_KEY",freshnessPolicy:"plan-defined",regionCoverage:["global"],dataBoundary:"Commercial rights depend on plan; raw redistribution is restricted.",termsUrl:"https://www.coingecko.com/en/terms",documentationUrl:"https://docs.coingecko.com/",reviewedAt }),
  provider({ id:"tmdb",name:"TMDB API",category:"entertainment",capabilities:["entertainment-metadata"],status:"experimental",auth:"api-key",baseUrl:"https://api.themoviedb.org",commercialUse:"review_required",freeTierUse:"not_available",sourceQuality:"aggregator",priority:10,adapterStatus:"planned",secretEnvName:"NEO_TMDB_KEY",freshnessPolicy:"provider-defined",regionCoverage:["global"],dataBoundary:"Developer API is non-commercial; commercial use requires agreement.",termsUrl:"https://www.themoviedb.org/api-terms-of-use",documentationUrl:"https://developer.themoviedb.org/docs",reviewedAt }),
  provider({ id:"nominatim-public",name:"OpenStreetMap Nominatim Public Service",category:"geocoding",capabilities:["geocoding"],status:"experimental",auth:"user-agent",baseUrl:"https://nominatim.openstreetmap.org",commercialUse:"review_required",freeTierUse:"evaluation_only",sourceQuality:"community",priority:10,adapterStatus:"planned",freshnessPolicy:"osm-dataset",regionCoverage:["global"],dataBoundary:"Public service has strict capacity/use limits; not a default shared production dependency.",termsUrl:"https://operations.osmfoundation.org/policies/nominatim/",documentationUrl:"https://nominatim.org/release-docs/latest/api/Overview/",reviewedAt }),
  provider({ id:"open-meteo-free",name:"Open-Meteo Free API",category:"weather",capabilities:["weather-forecast"],status:"experimental",auth:"none",baseUrl:"https://api.open-meteo.com",commercialUse:"blocked",freeTierUse:"not_available",sourceQuality:"aggregator",priority:30,adapterStatus:"planned",freshnessPolicy:"forecast-product-defined",regionCoverage:["global"],dataBoundary:"Free hosted endpoint is non-commercial; paid/self-hosted use is separate.",termsUrl:"https://open-meteo.com/en/terms",documentationUrl:"https://open-meteo.com/en/docs",reviewedAt }),
  provider({ id:"serpstack",name:"serpstack",category:"seo",capabilities:["seo-serp-discovery"],status:"blocked",auth:"api-key",baseUrl:"https://api.serpstack.com",commercialUse:"blocked",freeTierUse:"not_available",sourceQuality:"aggregator",priority:90,adapterStatus:"not_applicable",freshnessPolicy:"provider-defined",regionCoverage:["global"],dataBoundary:"Published terms do not meet Neo commercial production requirements.",termsUrl:"https://serpstack.com/terms",documentationUrl:"https://serpstack.com/documentation",reviewedAt }),
  provider({ id:"guardian-developer",name:"Guardian Open Platform Developer",category:"news",capabilities:["news-discovery"],status:"blocked",auth:"api-key",baseUrl:"https://content.guardianapis.com",commercialUse:"blocked",freeTierUse:"not_available",sourceQuality:"primary",priority:90,adapterStatus:"not_applicable",freshnessPolicy:"publisher-defined",regionCoverage:["global"],dataBoundary:"Developer access is non-commercial; commercial/AI-derived use requires separate access.",termsUrl:"https://open-platform.theguardian.com/access/",documentationUrl:"https://open-platform.theguardian.com/documentation/",reviewedAt }),
  provider({ id:"gnews-free",name:"GNews Free",category:"news",capabilities:["news-discovery"],status:"blocked",auth:"api-key",baseUrl:"https://gnews.io",commercialUse:"blocked",freeTierUse:"not_available",sourceQuality:"aggregator",priority:90,adapterStatus:"not_applicable",freshnessPolicy:"free-plan-delayed",regionCoverage:["global"],dataBoundary:"Free plan is development/testing only and not production eligible.",termsUrl:"https://gnews.io/terms",documentationUrl:"https://docs.gnews.io/",reviewedAt })
]);

export function providersFor(capability: string, options: { includeExperimental?: boolean } = {}): SourceProvider[] {
  return sourceRegistry.filter((p) => p.capabilities.includes(capability) && (p.status === "approved" || (options.includeExperimental && p.status === "experimental"))).sort((a,b) => a.priority-b.priority);
}

export function providerById(id: string): SourceProvider | undefined { return sourceRegistry.find((provider) => provider.id === id); }

export function safeRegistrySnapshot() {
  return sourceRegistry.map(({ secretEnvName: _secret, baseUrl: _base, ...safe }) => safe);
}
